say There seems to be some kind of park up ahead and I think of another dreamer\'s dare to fly like a bird and poo on a bald guy\'s head\. I descend a bit and start flapping my arms like a bird\. I see a few groups of people scattered about\. Near me is a little bathroom and an SUV parked next to it\. Some guy comes out of the bathroom and he has hair\, but then another guy comes out of the SUV and starts towards the bathroom and he\'s bald on top with a tiny bit of blonde-ish hair around the edges\. I descend to right above his head and begin to push\. A clump of round poops the color of sand comes out and lands right on his head\. The poops are kind of hard I guess\, so when they hit they just kind of explode away and leave no trace\. He flinches and looks up\. I start to sink involuntarily\, going to about head-level with this guy\. I push again and a single\, dark-grey poop ball flies out and up and over and hits him again right in the middle of his head\. He flinches again and I laugh\, flying away -o dream_01.aiff;
say I fly off the porch and hear a dog growling as it gives chase\. It can\'t fly after me yet, but I know that it may develop the ability to do so since it\'s a dream\. I turn forward again and there\'s a couple of Christmas-y fir trees growing in the yard\. Birds are nesting in the branches and fluttering back and forth\. I fly around the tree and little \"birds\" follow me\. They turn into little cartoonish beings\. Most of them is their head and face\. They are talking and singing\. One of them, a black one, has my Dad\'s voice\. It\'s kind of freaking me out, so I turn to it and say, \"Can you please stop using my Dad\'s voice\?\" Its eyebrows draw down and it responds in the negative\. -o dream_02.aiff
say We were walking down a path in a big forest when all of a sudden a huge bird, a hawk of some kind, came down and picked up my younger brother and carried him off to a nest\. My other brother and I stood there spellbound\. We ran back to our tent and got our \.22 rifle which we had brought along just for target practice\. We then ran to where the nest was and started to creep up on it when all of a sudden the bird took off with my younger brother\. He started to fly low out over a body of water\. I felt this would be the last time we would see him so I took my rifle and shot at the bird\. It let go of my brother and he fell into the lake\. He swam to the shore\. The bird fell into the water dead\. This is where my dream ended\. -o dream_03.aiff

say I looked up into the sky determined to fly and jumped\.  It was a bit difficult and I gained altitude pretty slowly, but I spread my arms, visualized rising up like an eagle riding a hot updraft and flew up and over a bridge\.  Some of the birds who were up there squawked and chirped at me, so I jokingly squeaked and chirped back\.  I got the feeling that we actually understood each other\. -o dream_04.aiff

say I was flying down a ski hill in the vertical position, about 5 to 10 feet above the slope, beside a friend, who was also flying\. Then a seagull came flying right over my head from the rear, only missing me by inches, then it turned around and mad another close pass\. I raised my arm for it to land, but instead, it landed on my head! Typical bird! We travelled like this for about a hundred yards, but its claws were digging into my head, and it was a bit annoying, so I raised my forearm up to it, so it would climb on, and it did! A short while later, I started to hug the seagull, and I could feel love radiating from this bird! I was getting all these memory flashes\. My friend flew in a bit closer and raised his forearm for the seagull, so I carefully passed him the bird\. The seagull climbed onto to his forearm, and it started to grow bigger and it began to morph into a person, but then it returned to bird state\. When we got to the bottom of the ski slope, the bird flew away, and we decided to land and go inside a ski chalet\. -o dream_05.aiff

say I shoot off in a random direction, seeking Pegasus\. I find myself flying swiftly along a small river\. I look ahead and there are geese flying on the same level with me and in the same direction, but quite a bit slower\. I pass by them, examining them\. I grab one by the neck and look at it up close before throwing it away\. Stop Dream Goose Abuse \(Aboose\?\) As I approached, their bodies had a grey and brown drab feather pattern and greyish legs\. When I got much closer, they\'d turned into Canadian geese and stayed that way\. I fly on ahead of them and see another flock of birds ahead--small black birds which turn into Pegasi\. I pursue them, but I think I get lost in the dream\. -o dream_06.aiff

say Next to a large red barn is a row of large birds\. They\'re probably about 8 feet tall\. Their bodies are that of a sleek, clean-legged game hen\. I notice one of the birds in the middle of the row has a white head\. I focus more and see it\'s a bald eagle\'s head\. I have some flashing thought of America and see the American flag\. I survey the birds more and now they all have bald eagle heads\. There are some dream characters standing to my right, facing the same way as me\. I point out the interesting birds to them\. -o dream_07.aiff

say I started to bake something for the baking competition that was going on in the room\. I think there were some anime characters doing this\. Sadly bird poop and food began to appear in the batter so i quit doing the competition\. -o dream_08.aiff

say She shows me a market place where a dark green blackish feather colored small chubby birdie was\.\" Can i touch him\?\"I ask\. My sister than appears and says \"Of course you can touch him\. That\'s why they put him there\.\" I grab him but then he hops off\. -o dream_09.aiff

say We had pets that were parrots\. There was a red parrot that i wanted so i asked W \"How do i get the red parrot\?\" W answered saying \"You just have to take care of it really good so that it can grow to like you\.\" I took the red bird and suddenly another guy came into the picture\. He started talking about the gray parrot and the red one\. -o dream_10.aiff

 say i was in a room where I saw a man sitting down appear\. He starts talking about parakeets\. A basket than appears in front of him\. \"Parakeets are tropical birds\. When it gets really cold its important they stay warm\. But not too warm\. You see the basket\'s material allows the basket to get really hot over time\. Which many owners forget\.\" I can see him holding a parakeet and getting a blood sample now\. \"I really need to get my parakeet checked out\" I think to myself\. But then i stare at the long needle and ask myself \"Why does he need all that blood\?\" -o dream_11.aiff 

say A small bird has flown into the house I\'m in\.  The woman I\'m with tries to catch it\.  Naturally, I assist\.  When it lands on a chair near me I place my finger in front of its belly\.  It steps up\.  I carry its scraggly body into a connected room that resembles the outside but when I step into it, it\'s more like an aviary\.  The bird jumps off my finger and finds other baby birds that are green, like itself\.  I have a look around the room when two very large, pterodactyl large, white birds fly in and seat themselves on the guardrail\.  One of them cants their head at me\.  I find myself doing the same to it\.  It relaxes and I continue to the opposite side of the overly large room\. A large white dog appears from nowhere, literally popping into existence right in front of me\.  I find this strange too but I\'m not overly invested in anything in this room\.\.besides the initial bird I carried in here\. -o dream_12.aiff

say I notice a bird coming towards me and think nothing of it\.  Until it begins pecking at me\.  I brush it off and change directions\.  The bird makes another pass\.  I focus on it and it changes form--from a black pigeon, to a crow, then to something the size of an eagle\.  I make a deliberate swipe and stop ignoring it\.  It buggers off but returns to sit on my back\.  The pecking has ceased so I continue walking\.  It asks me who I am\.  We chat for a good bit\.  I find it rather pleasant\. I walk the way I came but this time the scene is entirely different\.  I\'ve arrived at a cruise ship and there are people in this location\.  The bird goes to my opposite shoulder and climbs to the front of me\.  Eyes form on its belly and I count maybe a dozen eyes, each staring in their own given direction with occasional glances at me\.  The bird asks me another question\.  Something normal like, what size is my shirt or something\.  There was an issue hearing him, interference\.  Granted we were speaking telepathically but we\'re not alone now\.  Many others are near us, with thoughts of their own, and it\'s entirely too noisy for me to focus on just the bird\'s thoughts\.  By now I\'ve found an agenda so I brush the bird off--telling it to leave me\.  Not in a rude way but we are not friends, I do not trust it, I can sense that it\'s merely gathering information but I don\'t know why or to whom it reports\.  Being under surveillance by a crow that looks an awful lot like one of Miyazaki\'s mythical creations isn\'t a game I\'d like to play\.  The bird leaves\.  I find people\.  We chat\. -o dream_13.aiff

say The teacher walked in\. She lectured us for a little bit, and yelled at one of the students who didn\'t address her as \"ma\'am\"\. Then she decided to give us a quiz on \"10 differences between birds and humans\"\. -o dream_14.aiff

say I was brought to a place like an arena but inside a huge auditorium\. I walked pretty fast out the doors but a couple of guards saw me and brought me back to where the arena was\. A beast was then released and people began screaming and running all around\. I I knew it would be wrong to run so I decided to face the giant yellow and Orange colored bird\. As the bird was gobbling up lots of people, I ran and flew up to it trying to punch and kick it\. But the beak was too huge\. The bird started chasing me around even more now so I decided to use my fingers to shoot a flaming ball at it\. I charged it up flying backwards as it came at me and released the flame at it\. The flame ball missed though and exploded on the ground\. I tried charging another one but my powers weren\'t working\. So the bird cornered me, but I could see the bird was now changing into a man who yelled the fight was over and he won\. I wasn\'t ready to give up though so I jumped and punched him a couple times in the face\. -o dream_14.aiff

say There was a Indian man dressed in a huge blue bird suit doing a dance\. I tried to do his moves just for fun but he said I was doing it wrong\. -o dream_15.aiff

say I found myself in this small park area\. There are old ladies sitting everywhere with bread, throwing it on the ground\. I looked around and there was bird poo everywhere\. I wondered what could possibly make so much bird poo\. Then I saw that there were giant pigeons, about two feet tall when landed\. -o dream_16.aiff

say There was a coat rack with cages hanging from it there were brightly colored birds in them\. Some of the cages were open and a couple of exotic dream-birds were circling around the room\. -o dream_17.aiff

say We reached a place that looked devilish because of all the dead animals around\. I jumped down off a ledge and flew up to this pillar of dead animal\'s heads\. There was a crow with a very long orange yellow beak\. I grabbed the head of the crow, willing its beak to open\. I feared it would bite me, but it didn\'t\. I then put the bird\'s beak to a tree next to me and willed it to cut the tree in half\. It didn\'t\. -o dream_18.aiff

say There was something like a woodpecker-toy high on my shelf - not sure, if you know what I mean - a wooden bird on a spring and when you bend it back, it starts hacking away at the base it\'s mounted on\. It was the size of a dove, though, and started hacking all on its own, like in a poltergeist movie, where toys turn vicious\. -o dream_19.aiff

say Men are after me\. I manage to shrink myself into the size, and possibly the form, of a bird\. I\'ve moved my awareness outside of my body and am now observing myself run around in circles, much like a headless chicken\.   The men try their best to make a capture\. -o dream_20.aiff 

say We were talking about the creatures that you could mount including this huge eagle\. The creature has customization\. You can change different aspects of it such as the wings and the head to make it look more like a dragon or another creature, but no matter what you do, the graphic model always looks like a bird\. I recall this one option for the creature that makes the wings look distressed\. Some of the bird\'s feathers will be missing\. At this point, one of the large bird creatures comes down and lands on a large rock where we\'re talking\. It has the distressed wings and looks like some kind of zombie or demon because of the other options that have been picked\. -o dream_21.aiff 

say I walk around campus\.  In the center is a pool of water\.  I walk along the side of the pool and notice baby myna birds toppling over\. -o dream_22.aiff 

say Two frogs were trying to murder each other\. I had two options: Let the frogs kill each other, or kill them using a bird\. I chose the second one, and a bird came down and scooped up one of the frogs\. It came back after a second and was disappointed that the other frog wasn\'t there--I had killed the other one\. -o dream_23.aiff 

say I noticed that the walls were dirty with yellow stuff on it and thought i saw a picture of Tweety Bird\. -o dream_22.aiff 

say I had a dream about finding some robin eggs\. I brought them into the bedroom and showed them to Danny\. He said he believed that they had been fertilized already\. Sure enough, I looked at them and they had sticky stuff on the outside of the little pink shells\. \"EW!\" I dropped one on the floor and it cracked slightly\. I was worried that I might have hurt a potential little baby bird inside so I picked it up\. I was holding it in my right hand, when I suddenly seemed to be lying down\. I \"fell asleep\" in the dream, holding the slimy little egg\. -o dream_23.aiff

       

